<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntitiesRentaContratoProxy extends \Entities\RentaContrato implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setFechaPeriodo($fechaPeriodo)
    {
        $this->__load();
        return parent::setFechaPeriodo($fechaPeriodo);
    }

    public function getFechaPeriodo()
    {
        $this->__load();
        return parent::getFechaPeriodo();
    }

    public function setRentaBruta($rentaBruta)
    {
        $this->__load();
        return parent::setRentaBruta($rentaBruta);
    }

    public function getRentaBruta()
    {
        $this->__load();
        return parent::getRentaBruta();
    }

    public function setGratificacion($gratificacion)
    {
        $this->__load();
        return parent::setGratificacion($gratificacion);
    }

    public function getGratificacion()
    {
        $this->__load();
        return parent::getGratificacion();
    }

    public function setTipoContrato(\Entities\TipoContrato $tipoContrato)
    {
        $this->__load();
        return parent::setTipoContrato($tipoContrato);
    }

    public function getTipoContrato()
    {
        $this->__load();
        return parent::getTipoContrato();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'fecha_periodo', 'renta_bruta', 'gratificacion', 'tipoContrato');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}