<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntitiesContratoProxy extends \Entities\Contrato implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setFechaInicio($fechaInicio)
    {
        $this->__load();
        return parent::setFechaInicio($fechaInicio);
    }

    public function getFechaInicio()
    {
        $this->__load();
        return parent::getFechaInicio();
    }

    public function setFechaTermino($fechaTermino)
    {
        $this->__load();
        return parent::setFechaTermino($fechaTermino);
    }

    public function getFechaTermino()
    {
        $this->__load();
        return parent::getFechaTermino();
    }

    public function setTipoContrato(\Entities\TipoContrato $tipoContrato)
    {
        $this->__load();
        return parent::setTipoContrato($tipoContrato);
    }

    public function getTipoContrato()
    {
        $this->__load();
        return parent::getTipoContrato();
    }

    public function setEmpleado(\Entities\Empleado $empleado)
    {
        $this->__load();
        return parent::setEmpleado($empleado);
    }

    public function getEmpleado()
    {
        $this->__load();
        return parent::getEmpleado();
    }

    public function setPrevision(\Entities\Prevision $prevision)
    {
        $this->__load();
        return parent::setPrevision($prevision);
    }

    public function getPrevision()
    {
        $this->__load();
        return parent::getPrevision();
    }

    public function addPactosSalud(\Entities\PactoSalud $pactosSalud)
    {
        $this->__load();
        return parent::addPactosSalud($pactosSalud);
    }

    public function getPactosSalud()
    {
        $this->__load();
        return parent::getPactosSalud();
    }

    public function addRegistrosMensuales(\Entities\RegistroMensual $registrosMensuales)
    {
        $this->__load();
        return parent::addRegistrosMensuales($registrosMensuales);
    }

    public function getRegistrosMensuales()
    {
        $this->__load();
        return parent::getRegistrosMensuales();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'fecha_inicio', 'fecha_termino', 'tipoContrato', 'pactosSalud', 'registrosMensuales', 'empleado', 'prevision');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}